server:
  port: 8083

spring:
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
#spring:
#    datasource:
#        driver-class-name: com.mysql.jdbc.Driver
#        password: root
#        url: jdbc:mysql://localhost:3306/keycloak
#        username: root

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: admin
      password: admin
    realmImportFile: realm-export.json
